# Makefile autogenerated by Dyi on May 5, 2015
#
# Main target: all
# Sources: 

.DEFAULT_GOAL := all


.PHONY: all
all: k-8q49m9h0


.PHONY: clean
clean: k-enlm4w5l k-ax0se4mr


.PHONY: prepare
prepare:




.PHONY: k-8q49m9h0
k-8q49m9h0:  
	clash --vhdl aes.hs


.PHONY: k-enlm4w5l
k-enlm4w5l:  
	rm -rf vhdl


.PHONY: k-ax0se4mr
k-ax0se4mr:  
	rm *.hi *.o *.hs *.s


.PHONY: update
update: 
	make clean   
	node /Users/zaccaria/development/github/clash-sandbox/configure.js




