# Makefile autogenerated by Dyi on May 20, 2015
#
# Main target: all
# Sources: 

.DEFAULT_GOAL := all


.PHONY: all
all: k-qti66ooe k-nrbh3bo7


.PHONY: c-nuuya2c9
c-nuuya2c9:


.PHONY: doc
doc: c-nuuya2c9


.PHONY: edit
edit: k-m7883c2w


.PHONY: clean
clean: k-xqxv0ido k-1kt07lkv


.PHONY: prepare
prepare:




.PHONY: k-qti66ooe
k-qti66ooe:  
	clash -cpp -DCLASH -iCrypto --vhdl Crypto/AES.hs


.PHONY: k-nrbh3bo7
k-nrbh3bo7:  
	cat vhdl/AES/zuzdzf_4.vhdl


.PHONY: k-m7883c2w
k-m7883c2w:  
	watchman Crypto 'make doc && chromereload'


.PHONY: k-xqxv0ido
k-xqxv0ido:  
	rm -rf vhdl


.PHONY: k-1kt07lkv
k-1kt07lkv:  
	rm -f *.hi *.o *.s


.PHONY: update
update: 
	make clean   
	node




