# Makefile autogenerated by Dyi on May 19, 2015
#
# Main target: all
# Sources: 

.DEFAULT_GOAL := all


.PHONY: all
all: k-j6c6p1vs k-gthfeyyh


.PHONY: c-epa6p0v3
c-epa6p0v3:


.PHONY: doc
doc: c-epa6p0v3


.PHONY: edit
edit: k-ghd49c8h


.PHONY: clean
clean: k-eythqofe k-x5qehv4w


.PHONY: prepare
prepare:




.PHONY: k-j6c6p1vs
k-j6c6p1vs:  
	clash -iCrypto --vhdl Crypto/AES.hs


.PHONY: k-gthfeyyh
k-gthfeyyh:  
	cat vhdl/AES/zuzdzf_4.vhdl


.PHONY: k-ghd49c8h
k-ghd49c8h:  
	watchman Crypto 'make doc && chromereload'


.PHONY: k-eythqofe
k-eythqofe:  
	rm -rf vhdl


.PHONY: k-x5qehv4w
k-x5qehv4w:  
	rm -f *.hi *.o *.s


.PHONY: update
update: 
	make clean   
	node




